//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aphia/v1.0", ConfigurationName="Worms.AphiaNameServicePortType")]
    public interface AphiaNameServicePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaID) of message getAphiaIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Worms.getAphiaIDResponse getAphiaID(Worms.getAphiaIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecords) of message getAphiaRecordsRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaRecordsResponse getAphiaRecords(Worms.getAphiaRecordsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaName) of message getAphiaNameByIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaNameByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaNameByIDResponse getAphiaNameByID(Worms.getAphiaNameByIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecord) of message getAphiaRecordByIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaRecordByIDResponse getAphiaRecordByID(Worms.getAphiaRecordByIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecord) of message getAphiaRecordByExtIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordByExtID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaRecordByExtIDResponse getAphiaRecordByExtID(Worms.getAphiaRecordByExtIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/externalidentifiers) of message getExtIDbyAphiaIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getExtIDbyAphiaID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getExtIDbyAphiaIDResponse getExtIDbyAphiaID(Worms.getExtIDbyAphiaIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaMatches) of message getAphiaRecordsByNamesRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordsByNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaRecordsByNamesResponse getAphiaRecordsByNames(Worms.getAphiaRecordsByNamesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecords) of message getAphiaRecordsByVernacularRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordsByVernacular", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaRecordsByVernacularResponse getAphiaRecordsByVernacular(Worms.getAphiaRecordsByVernacularRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecords) of message getAphiaRecordsByDateRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordsByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaRecordsByDateResponse getAphiaRecordsByDate(Worms.getAphiaRecordsByDateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/Classification) of message getAphiaClassificationByIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaClassificationByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaClassificationByIDResponse getAphiaClassificationByID(Worms.getAphiaClassificationByIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/Sources) of message getSourcesByAphiaIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getSourcesByAphiaID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getSourcesByAphiaIDResponse getSourcesByAphiaID(Worms.getSourcesByAphiaIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecords) of message getAphiaSynonymsByIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaSynonymsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaSynonymsByIDResponse getAphiaSynonymsByID(Worms.getAphiaSynonymsByIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaVernaculars) of message getAphiaVernacularsByIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaVernacularsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaVernacularsByIDResponse getAphiaVernacularsByID(Worms.getAphiaVernacularsByIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecords) of message getAphiaChildrenByIDRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaChildrenByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.getAphiaChildrenByIDResponse getAphiaChildrenByID(Worms.getAphiaChildrenByIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaMatches) of message matchAphiaRecordsByNamesRequest does not match the default value (http://aphia/v1.0)
        [System.ServiceModel.OperationContractAttribute(Action="matchAphiaRecordsByNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        Worms.matchAphiaRecordsByNamesResponse matchAphiaRecordsByNames(Worms.matchAphiaRecordsByNamesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaID", WrapperNamespace="http://aphia/v1.0/AphiaID", IsWrapped=true)]
    public partial class getAphiaIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string scientificname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool marine_only;
        
        public getAphiaIDRequest() {
        }
        
        public getAphiaIDRequest(string scientificname, bool marine_only) {
            this.scientificname = scientificname;
            this.marine_only = marine_only;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaID", IsWrapped=true)]
    public partial class getAphiaIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public getAphiaIDResponse() {
        }
        
        public getAphiaIDResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class AphiaRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int aphiaIDField;
        
        private string urlField;
        
        private string scientificnameField;
        
        private string authorityField;
        
        private string rankField;
        
        private string statusField;
        
        private string unacceptreasonField;
        
        private int valid_AphiaIDField;
        
        private string valid_nameField;
        
        private string valid_authorityField;
        
        private string kingdomField;
        
        private string phylumField;
        
        private string classField;
        
        private string orderField;
        
        private string familyField;
        
        private string genusField;
        
        private string citationField;
        
        private string lsidField;
        
        private int isMarineField;
        
        private int isBrackishField;
        
        private int isFreshwaterField;
        
        private int isTerrestrialField;
        
        private int isExtinctField;
        
        private string match_typeField;
        
        private string modifiedField;
        
        /// <remarks/>
        public int AphiaID {
            get {
                return this.aphiaIDField;
            }
            set {
                this.aphiaIDField = value;
                this.RaisePropertyChanged("AphiaID");
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        public string scientificname {
            get {
                return this.scientificnameField;
            }
            set {
                this.scientificnameField = value;
                this.RaisePropertyChanged("scientificname");
            }
        }
        
        /// <remarks/>
        public string authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
                this.RaisePropertyChanged("authority");
            }
        }
        
        /// <remarks/>
        public string rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("rank");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        public string unacceptreason {
            get {
                return this.unacceptreasonField;
            }
            set {
                this.unacceptreasonField = value;
                this.RaisePropertyChanged("unacceptreason");
            }
        }
        
        /// <remarks/>
        public int valid_AphiaID {
            get {
                return this.valid_AphiaIDField;
            }
            set {
                this.valid_AphiaIDField = value;
                this.RaisePropertyChanged("valid_AphiaID");
            }
        }
        
        /// <remarks/>
        public string valid_name {
            get {
                return this.valid_nameField;
            }
            set {
                this.valid_nameField = value;
                this.RaisePropertyChanged("valid_name");
            }
        }
        
        /// <remarks/>
        public string valid_authority {
            get {
                return this.valid_authorityField;
            }
            set {
                this.valid_authorityField = value;
                this.RaisePropertyChanged("valid_authority");
            }
        }
        
        /// <remarks/>
        public string kingdom {
            get {
                return this.kingdomField;
            }
            set {
                this.kingdomField = value;
                this.RaisePropertyChanged("kingdom");
            }
        }
        
        /// <remarks/>
        public string phylum {
            get {
                return this.phylumField;
            }
            set {
                this.phylumField = value;
                this.RaisePropertyChanged("phylum");
            }
        }
        
        /// <remarks/>
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        public string order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("order");
            }
        }
        
        /// <remarks/>
        public string family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
                this.RaisePropertyChanged("family");
            }
        }
        
        /// <remarks/>
        public string genus {
            get {
                return this.genusField;
            }
            set {
                this.genusField = value;
                this.RaisePropertyChanged("genus");
            }
        }
        
        /// <remarks/>
        public string citation {
            get {
                return this.citationField;
            }
            set {
                this.citationField = value;
                this.RaisePropertyChanged("citation");
            }
        }
        
        /// <remarks/>
        public string lsid {
            get {
                return this.lsidField;
            }
            set {
                this.lsidField = value;
                this.RaisePropertyChanged("lsid");
            }
        }
        
        /// <remarks/>
        public int isMarine {
            get {
                return this.isMarineField;
            }
            set {
                this.isMarineField = value;
                this.RaisePropertyChanged("isMarine");
            }
        }
        
        /// <remarks/>
        public int isBrackish {
            get {
                return this.isBrackishField;
            }
            set {
                this.isBrackishField = value;
                this.RaisePropertyChanged("isBrackish");
            }
        }
        
        /// <remarks/>
        public int isFreshwater {
            get {
                return this.isFreshwaterField;
            }
            set {
                this.isFreshwaterField = value;
                this.RaisePropertyChanged("isFreshwater");
            }
        }
        
        /// <remarks/>
        public int isTerrestrial {
            get {
                return this.isTerrestrialField;
            }
            set {
                this.isTerrestrialField = value;
                this.RaisePropertyChanged("isTerrestrial");
            }
        }
        
        /// <remarks/>
        public int isExtinct {
            get {
                return this.isExtinctField;
            }
            set {
                this.isExtinctField = value;
                this.RaisePropertyChanged("isExtinct");
            }
        }
        
        /// <remarks/>
        public string match_type {
            get {
                return this.match_typeField;
            }
            set {
                this.match_typeField = value;
                this.RaisePropertyChanged("match_type");
            }
        }
        
        /// <remarks/>
        public string modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
                this.RaisePropertyChanged("modified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class Vernacular : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vernacularField;
        
        private string language_codeField;
        
        private string languageField;
        
        /// <remarks/>
        public string vernacular {
            get {
                return this.vernacularField;
            }
            set {
                this.vernacularField = value;
                this.RaisePropertyChanged("vernacular");
            }
        }
        
        /// <remarks/>
        public string language_code {
            get {
                return this.language_codeField;
            }
            set {
                this.language_codeField = value;
                this.RaisePropertyChanged("language_code");
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class Source : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int source_idField;
        
        private string useField;
        
        private string referenceField;
        
        private string pageField;
        
        private string urlField;
        
        private string linkField;
        
        private string fulltextField;
        
        /// <remarks/>
        public int source_id {
            get {
                return this.source_idField;
            }
            set {
                this.source_idField = value;
                this.RaisePropertyChanged("source_id");
            }
        }
        
        /// <remarks/>
        public string use {
            get {
                return this.useField;
            }
            set {
                this.useField = value;
                this.RaisePropertyChanged("use");
            }
        }
        
        /// <remarks/>
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        public string page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
        
        /// <remarks/>
        public string fulltext {
            get {
                return this.fulltextField;
            }
            set {
                this.fulltextField = value;
                this.RaisePropertyChanged("fulltext");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class Classification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int aphiaIDField;
        
        private string rankField;
        
        private string scientificnameField;
        
        private Classification childField;
        
        /// <remarks/>
        public int AphiaID {
            get {
                return this.aphiaIDField;
            }
            set {
                this.aphiaIDField = value;
                this.RaisePropertyChanged("AphiaID");
            }
        }
        
        /// <remarks/>
        public string rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("rank");
            }
        }
        
        /// <remarks/>
        public string scientificname {
            get {
                return this.scientificnameField;
            }
            set {
                this.scientificnameField = value;
                this.RaisePropertyChanged("scientificname");
            }
        }
        
        /// <remarks/>
        public Classification child {
            get {
                return this.childField;
            }
            set {
                this.childField = value;
                this.RaisePropertyChanged("child");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecords", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string scientificname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool like;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public bool fuzzy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public bool marine_only;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int offset;
        
        public getAphiaRecordsRequest() {
        }
        
        public getAphiaRecordsRequest(string scientificname, bool like, bool fuzzy, bool marine_only, int offset) {
            this.scientificname = scientificname;
            this.like = like;
            this.fuzzy = fuzzy;
            this.marine_only = marine_only;
            this.offset = offset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.AphiaRecord[] @return;
        
        public getAphiaRecordsResponse() {
        }
        
        public getAphiaRecordsResponse(Worms.AphiaRecord[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaNameByID", WrapperNamespace="http://aphia/v1.0/AphiaName", IsWrapped=true)]
    public partial class getAphiaNameByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaNameByIDRequest() {
        }
        
        public getAphiaNameByIDRequest(int AphiaID) {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaNameByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaName", IsWrapped=true)]
    public partial class getAphiaNameByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getAphiaNameByIDResponse() {
        }
        
        public getAphiaNameByIDResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordByID", WrapperNamespace="http://aphia/v1.0/AphiaRecord", IsWrapped=true)]
    public partial class getAphiaRecordByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaRecordByIDRequest() {
        }
        
        public getAphiaRecordByIDRequest(int AphiaID) {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecord", IsWrapped=true)]
    public partial class getAphiaRecordByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.AphiaRecord @return;
        
        public getAphiaRecordByIDResponse() {
        }
        
        public getAphiaRecordByIDResponse(Worms.AphiaRecord @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordByExtID", WrapperNamespace="http://aphia/v1.0/AphiaRecord", IsWrapped=true)]
    public partial class getAphiaRecordByExtIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string type;
        
        public getAphiaRecordByExtIDRequest() {
        }
        
        public getAphiaRecordByExtIDRequest(string id, string type) {
            this.id = id;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordByExtIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecord", IsWrapped=true)]
    public partial class getAphiaRecordByExtIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.AphiaRecord @return;
        
        public getAphiaRecordByExtIDResponse() {
        }
        
        public getAphiaRecordByExtIDResponse(Worms.AphiaRecord @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getExtIDbyAphiaID", WrapperNamespace="http://aphia/v1.0/externalidentifiers", IsWrapped=true)]
    public partial class getExtIDbyAphiaIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string type;
        
        public getExtIDbyAphiaIDRequest() {
        }
        
        public getExtIDbyAphiaIDRequest(int AphiaID, string type) {
            this.AphiaID = AphiaID;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getExtIDbyAphiaIDResponse", WrapperNamespace="http://aphia/v1.0/externalidentifiers", IsWrapped=true)]
    public partial class getExtIDbyAphiaIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] @return;
        
        public getExtIDbyAphiaIDResponse() {
        }
        
        public getExtIDbyAphiaIDResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByNames", WrapperNamespace="http://aphia/v1.0/AphiaMatches", IsWrapped=true)]
    public partial class getAphiaRecordsByNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] scientificnames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool like;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public bool fuzzy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public bool marine_only;
        
        public getAphiaRecordsByNamesRequest() {
        }
        
        public getAphiaRecordsByNamesRequest(string[] scientificnames, bool like, bool fuzzy, bool marine_only) {
            this.scientificnames = scientificnames;
            this.like = like;
            this.fuzzy = fuzzy;
            this.marine_only = marine_only;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByNamesResponse", WrapperNamespace="http://aphia/v1.0/AphiaMatches", IsWrapped=true)]
    public partial class getAphiaRecordsByNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.AphiaRecord[][] @return;
        
        public getAphiaRecordsByNamesResponse() {
        }
        
        public getAphiaRecordsByNamesResponse(Worms.AphiaRecord[][] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByVernacular", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsByVernacularRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string vernacular;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool like;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int offset;
        
        public getAphiaRecordsByVernacularRequest() {
        }
        
        public getAphiaRecordsByVernacularRequest(string vernacular, bool like, int offset) {
            this.vernacular = vernacular;
            this.like = like;
            this.offset = offset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByVernacularResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsByVernacularResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.AphiaRecord[] @return;
        
        public getAphiaRecordsByVernacularResponse() {
        }
        
        public getAphiaRecordsByVernacularResponse(Worms.AphiaRecord[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByDate", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string enddate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public bool marine_only;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int offset;
        
        public getAphiaRecordsByDateRequest() {
        }
        
        public getAphiaRecordsByDateRequest(string startdate, string enddate, bool marine_only, int offset) {
            this.startdate = startdate;
            this.enddate = enddate;
            this.marine_only = marine_only;
            this.offset = offset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByDateResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.AphiaRecord[] @return;
        
        public getAphiaRecordsByDateResponse() {
        }
        
        public getAphiaRecordsByDateResponse(Worms.AphiaRecord[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaClassificationByID", WrapperNamespace="http://aphia/v1.0/Classification", IsWrapped=true)]
    public partial class getAphiaClassificationByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaClassificationByIDRequest() {
        }
        
        public getAphiaClassificationByIDRequest(int AphiaID) {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaClassificationByIDResponse", WrapperNamespace="http://aphia/v1.0/Classification", IsWrapped=true)]
    public partial class getAphiaClassificationByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.Classification @return;
        
        public getAphiaClassificationByIDResponse() {
        }
        
        public getAphiaClassificationByIDResponse(Worms.Classification @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSourcesByAphiaID", WrapperNamespace="http://aphia/v1.0/Sources", IsWrapped=true)]
    public partial class getSourcesByAphiaIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getSourcesByAphiaIDRequest() {
        }
        
        public getSourcesByAphiaIDRequest(int AphiaID) {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSourcesByAphiaIDResponse", WrapperNamespace="http://aphia/v1.0/Sources", IsWrapped=true)]
    public partial class getSourcesByAphiaIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.Source[] @return;
        
        public getSourcesByAphiaIDResponse() {
        }
        
        public getSourcesByAphiaIDResponse(Worms.Source[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaSynonymsByID", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaSynonymsByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaSynonymsByIDRequest() {
        }
        
        public getAphiaSynonymsByIDRequest(int AphiaID) {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaSynonymsByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaSynonymsByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.AphiaRecord[] @return;
        
        public getAphiaSynonymsByIDResponse() {
        }
        
        public getAphiaSynonymsByIDResponse(Worms.AphiaRecord[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaVernacularsByID", WrapperNamespace="http://aphia/v1.0/AphiaVernaculars", IsWrapped=true)]
    public partial class getAphiaVernacularsByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaVernacularsByIDRequest() {
        }
        
        public getAphiaVernacularsByIDRequest(int AphiaID) {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaVernacularsByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaVernaculars", IsWrapped=true)]
    public partial class getAphiaVernacularsByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.Vernacular[] @return;
        
        public getAphiaVernacularsByIDResponse() {
        }
        
        public getAphiaVernacularsByIDResponse(Worms.Vernacular[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaChildrenByID", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaChildrenByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int offset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public bool marine_only;
        
        public getAphiaChildrenByIDRequest() {
        }
        
        public getAphiaChildrenByIDRequest(int AphiaID, int offset, bool marine_only) {
            this.AphiaID = AphiaID;
            this.offset = offset;
            this.marine_only = marine_only;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaChildrenByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaChildrenByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.AphiaRecord[] @return;
        
        public getAphiaChildrenByIDResponse() {
        }
        
        public getAphiaChildrenByIDResponse(Worms.AphiaRecord[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="matchAphiaRecordsByNames", WrapperNamespace="http://aphia/v1.0/AphiaMatches", IsWrapped=true)]
    public partial class matchAphiaRecordsByNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] scientificnames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool marine_only;
        
        public matchAphiaRecordsByNamesRequest() {
        }
        
        public matchAphiaRecordsByNamesRequest(string[] scientificnames, bool marine_only) {
            this.scientificnames = scientificnames;
            this.marine_only = marine_only;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="matchAphiaRecordsByNamesResponse", WrapperNamespace="http://aphia/v1.0/AphiaMatches", IsWrapped=true)]
    public partial class matchAphiaRecordsByNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Worms.AphiaRecord[][] @return;
        
        public matchAphiaRecordsByNamesResponse() {
        }
        
        public matchAphiaRecordsByNamesResponse(Worms.AphiaRecord[][] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AphiaNameServicePortTypeChannel : Worms.AphiaNameServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AphiaNameServicePortTypeClient : System.ServiceModel.ClientBase<Worms.AphiaNameServicePortType>, Worms.AphiaNameServicePortType {
        
        public AphiaNameServicePortTypeClient() {
        }
        
        public AphiaNameServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AphiaNameServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AphiaNameServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AphiaNameServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaIDResponse Worms.AphiaNameServicePortType.getAphiaID(Worms.getAphiaIDRequest request) {
            return base.Channel.getAphiaID(request);
        }
        
        public int getAphiaID(string scientificname, bool marine_only) {
            Worms.getAphiaIDRequest inValue = new Worms.getAphiaIDRequest();
            inValue.scientificname = scientificname;
            inValue.marine_only = marine_only;
            Worms.getAphiaIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaRecordsResponse Worms.AphiaNameServicePortType.getAphiaRecords(Worms.getAphiaRecordsRequest request) {
            return base.Channel.getAphiaRecords(request);
        }
        
        public Worms.AphiaRecord[] getAphiaRecords(string scientificname, bool like, bool fuzzy, bool marine_only, int offset) {
            Worms.getAphiaRecordsRequest inValue = new Worms.getAphiaRecordsRequest();
            inValue.scientificname = scientificname;
            inValue.like = like;
            inValue.fuzzy = fuzzy;
            inValue.marine_only = marine_only;
            inValue.offset = offset;
            Worms.getAphiaRecordsResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaRecords(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaNameByIDResponse Worms.AphiaNameServicePortType.getAphiaNameByID(Worms.getAphiaNameByIDRequest request) {
            return base.Channel.getAphiaNameByID(request);
        }
        
        public string getAphiaNameByID(int AphiaID) {
            Worms.getAphiaNameByIDRequest inValue = new Worms.getAphiaNameByIDRequest();
            inValue.AphiaID = AphiaID;
            Worms.getAphiaNameByIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaNameByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaRecordByIDResponse Worms.AphiaNameServicePortType.getAphiaRecordByID(Worms.getAphiaRecordByIDRequest request) {
            return base.Channel.getAphiaRecordByID(request);
        }
        
        public Worms.AphiaRecord getAphiaRecordByID(int AphiaID) {
            Worms.getAphiaRecordByIDRequest inValue = new Worms.getAphiaRecordByIDRequest();
            inValue.AphiaID = AphiaID;
            Worms.getAphiaRecordByIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaRecordByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaRecordByExtIDResponse Worms.AphiaNameServicePortType.getAphiaRecordByExtID(Worms.getAphiaRecordByExtIDRequest request) {
            return base.Channel.getAphiaRecordByExtID(request);
        }
        
        public Worms.AphiaRecord getAphiaRecordByExtID(string id, string type) {
            Worms.getAphiaRecordByExtIDRequest inValue = new Worms.getAphiaRecordByExtIDRequest();
            inValue.id = id;
            inValue.type = type;
            Worms.getAphiaRecordByExtIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaRecordByExtID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getExtIDbyAphiaIDResponse Worms.AphiaNameServicePortType.getExtIDbyAphiaID(Worms.getExtIDbyAphiaIDRequest request) {
            return base.Channel.getExtIDbyAphiaID(request);
        }
        
        public string[] getExtIDbyAphiaID(int AphiaID, string type) {
            Worms.getExtIDbyAphiaIDRequest inValue = new Worms.getExtIDbyAphiaIDRequest();
            inValue.AphiaID = AphiaID;
            inValue.type = type;
            Worms.getExtIDbyAphiaIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getExtIDbyAphiaID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaRecordsByNamesResponse Worms.AphiaNameServicePortType.getAphiaRecordsByNames(Worms.getAphiaRecordsByNamesRequest request) {
            return base.Channel.getAphiaRecordsByNames(request);
        }
        
        public Worms.AphiaRecord[][] getAphiaRecordsByNames(string[] scientificnames, bool like, bool fuzzy, bool marine_only) {
            Worms.getAphiaRecordsByNamesRequest inValue = new Worms.getAphiaRecordsByNamesRequest();
            inValue.scientificnames = scientificnames;
            inValue.like = like;
            inValue.fuzzy = fuzzy;
            inValue.marine_only = marine_only;
            Worms.getAphiaRecordsByNamesResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaRecordsByNames(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaRecordsByVernacularResponse Worms.AphiaNameServicePortType.getAphiaRecordsByVernacular(Worms.getAphiaRecordsByVernacularRequest request) {
            return base.Channel.getAphiaRecordsByVernacular(request);
        }
        
        public Worms.AphiaRecord[] getAphiaRecordsByVernacular(string vernacular, bool like, int offset) {
            Worms.getAphiaRecordsByVernacularRequest inValue = new Worms.getAphiaRecordsByVernacularRequest();
            inValue.vernacular = vernacular;
            inValue.like = like;
            inValue.offset = offset;
            Worms.getAphiaRecordsByVernacularResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaRecordsByVernacular(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaRecordsByDateResponse Worms.AphiaNameServicePortType.getAphiaRecordsByDate(Worms.getAphiaRecordsByDateRequest request) {
            return base.Channel.getAphiaRecordsByDate(request);
        }
        
        public Worms.AphiaRecord[] getAphiaRecordsByDate(string startdate, string enddate, bool marine_only, int offset) {
            Worms.getAphiaRecordsByDateRequest inValue = new Worms.getAphiaRecordsByDateRequest();
            inValue.startdate = startdate;
            inValue.enddate = enddate;
            inValue.marine_only = marine_only;
            inValue.offset = offset;
            Worms.getAphiaRecordsByDateResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaRecordsByDate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaClassificationByIDResponse Worms.AphiaNameServicePortType.getAphiaClassificationByID(Worms.getAphiaClassificationByIDRequest request) {
            return base.Channel.getAphiaClassificationByID(request);
        }
        
        public Worms.Classification getAphiaClassificationByID(int AphiaID) {
            Worms.getAphiaClassificationByIDRequest inValue = new Worms.getAphiaClassificationByIDRequest();
            inValue.AphiaID = AphiaID;
            Worms.getAphiaClassificationByIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaClassificationByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getSourcesByAphiaIDResponse Worms.AphiaNameServicePortType.getSourcesByAphiaID(Worms.getSourcesByAphiaIDRequest request) {
            return base.Channel.getSourcesByAphiaID(request);
        }
        
        public Worms.Source[] getSourcesByAphiaID(int AphiaID) {
            Worms.getSourcesByAphiaIDRequest inValue = new Worms.getSourcesByAphiaIDRequest();
            inValue.AphiaID = AphiaID;
            Worms.getSourcesByAphiaIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getSourcesByAphiaID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaSynonymsByIDResponse Worms.AphiaNameServicePortType.getAphiaSynonymsByID(Worms.getAphiaSynonymsByIDRequest request) {
            return base.Channel.getAphiaSynonymsByID(request);
        }
        
        public Worms.AphiaRecord[] getAphiaSynonymsByID(int AphiaID) {
            Worms.getAphiaSynonymsByIDRequest inValue = new Worms.getAphiaSynonymsByIDRequest();
            inValue.AphiaID = AphiaID;
            Worms.getAphiaSynonymsByIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaSynonymsByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaVernacularsByIDResponse Worms.AphiaNameServicePortType.getAphiaVernacularsByID(Worms.getAphiaVernacularsByIDRequest request) {
            return base.Channel.getAphiaVernacularsByID(request);
        }
        
        public Worms.Vernacular[] getAphiaVernacularsByID(int AphiaID) {
            Worms.getAphiaVernacularsByIDRequest inValue = new Worms.getAphiaVernacularsByIDRequest();
            inValue.AphiaID = AphiaID;
            Worms.getAphiaVernacularsByIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaVernacularsByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.getAphiaChildrenByIDResponse Worms.AphiaNameServicePortType.getAphiaChildrenByID(Worms.getAphiaChildrenByIDRequest request) {
            return base.Channel.getAphiaChildrenByID(request);
        }
        
        public Worms.AphiaRecord[] getAphiaChildrenByID(int AphiaID, int offset, bool marine_only) {
            Worms.getAphiaChildrenByIDRequest inValue = new Worms.getAphiaChildrenByIDRequest();
            inValue.AphiaID = AphiaID;
            inValue.offset = offset;
            inValue.marine_only = marine_only;
            Worms.getAphiaChildrenByIDResponse retVal = ((Worms.AphiaNameServicePortType)(this)).getAphiaChildrenByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Worms.matchAphiaRecordsByNamesResponse Worms.AphiaNameServicePortType.matchAphiaRecordsByNames(Worms.matchAphiaRecordsByNamesRequest request) {
            return base.Channel.matchAphiaRecordsByNames(request);
        }
        
        public Worms.AphiaRecord[][] matchAphiaRecordsByNames(string[] scientificnames, bool marine_only) {
            Worms.matchAphiaRecordsByNamesRequest inValue = new Worms.matchAphiaRecordsByNamesRequest();
            inValue.scientificnames = scientificnames;
            inValue.marine_only = marine_only;
            Worms.matchAphiaRecordsByNamesResponse retVal = ((Worms.AphiaNameServicePortType)(this)).matchAphiaRecordsByNames(inValue);
            return retVal.@return;
        }
    }
}
